default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_App_development

test:
  <<: *default
  database: Budget_App_test

production:
  <<: *default
  database: Budget_App_production
  host: localhost
  port: 5432
